providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    defaultRule: "Host(` {{ trimPrefix `/` .Name }}.docker.localhost`)"
    exposedByDefault: false
    watch: true

  file:  
    filename: /etc/traefik/dyn.yml
  

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

api:
  dashboard: true
  insecure: true
  debug: true
